name: flutter_basic_app
description: A basic Flutter App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# Install dependencies from https://pub.dev/
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.2
  get_it: ^4.0.4 # Service Locator Library
  http: ^0.12.2 # https://pub.dev/packages/http
  http_interceptor: ^0.3.2 # https://pub.dev/packages/http_interceptor
  fluro: ^1.6.3 # https://pub.dev/packages/fluro
  cupertino_icons: ^0.1.3
  json_annotation: ^3.0.1 # runtime part of json_serializable # https://pub.dev/packages/json_annotation
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  equatable: ^1.2.3
  formz: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0 # https://pub.dev/packages/json_serializable
  build_runner: ^1.10.0 # dependency of json_serializable # https://pub.dev/packages/build_runner/install
  bloc_test: ^7.0.0
  mockito: ^4.1.1

flutter:
  uses-material-design: true

#  assets:
#    - images/...

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/Open_Sans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/Open_Sans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Open_Sans/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/Open_Sans/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Open_Sans/OpenSans-SemiBold.ttf
          weight: 600